server {
  listen 80;
  root /usr/share/nginx/html;
  location = /sw.js {
    add_header Cache-Control "no-cache";
  }
  location = /manifest.webmanifest {
    add_header Cache-Control "no-cache";
    default_type application/manifest+json;
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
}
